# Frontend production Dockerfile with NGINX

FROM node:16 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for the production app
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



