# Backend Dockerfile

FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose the backend's port
EXPOSE 5000

# Start the backend
CMD ["npm", "start"]
